### ISSUE TITLE
9.0 build error 

### ISSUE THREAD

**Issue by IronSharpensIron2717** [GZOSP-Devices/device_oneplus_enchilada#1]
i'm getting this, am i missing something from gerrit? 
FAILED: /home/rc420head/ssdraid/gzosp/out/target/product/enchilada/obj/PACKAGING/target_files_intermediates/gzosp_enchilada-target_files-512f136b13.zip 
/bin/bash -c "(if [ -d /home/rc420head/ssdraid/gzosp/out/target/product/enchilada/system/vendor ] && [ ! -h /home/rc420head/ssdraid/gzosp/out/target/product/enchilada/system/vendor ]; then echo 'Non-symlink /home/rc420head/ssdraid/gzosp/out/target/product/enchilada/system/vendor detected!' 1>&2; echo 'You cannot install files to /home/rc420head/ssdraid/gzosp/out/target/product/enchilada/system/vendor while building a separate vendor.img!' 1>&2; exit 1;

**Comment by anayw2001** [comment]
you may have to change TARGET_COPY_OUT_VENDOR to vendor

**Comment by anayw2001** [comment]
nevermind oof

**Comment by hardwareadictos** [comment]
Yes, we are having some troubles for making the zip package. Maybe some otapackage stuff

**Comment by Martinusbe** [comment]
fix it @hardwareadictos

**Comment by hardwareadictos** [comment]
> you may have to change TARGET_COPY_OUT_VENDOR to vendor

https://github.com/GZOSP-Devices/device_oneplus_sdm845-common/blob/9.0/BoardConfigCommon.mk#L92

**Comment by anayw2001** [comment]
Haha I looked at the common tree after and found it whoops

**Comment by Martinusbe** [comment]
build/core/makefile probably has something fishy

**Comment by hardwareadictos** [comment]
Build zip generation fixed. Closed
